# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-12 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
