# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-21 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import onlinestore.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0002_item_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='items')
            ),
    ]
