# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-22 00:05
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0003_auto_20181121_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='items'),
        ),
    ]
